#!/bin/bash

ACTION=$1

if [ "$ACTION" == "save" ]; then

	/sbin/iptables-save > /etc/iptables/iptables
	/sbin/ip6tables-save > /etc/iptables/ip6tables

fi

if [ "$ACTION" == "restore" ]; then

	/sbin/iptables-restore /etc/iptables/iptables
	/sbin/ip6tables-restore /etc/iptables/ip6tables

fi
